import Head from "next/head";
import RegularLayout from "@/layout/regularLayout";
import CategoriesSection from "@/components/sections/Categories/CategoriesSection";
import HeroSection from "@/components/sections/Hero/HeroSection";
import StatsSection from "@/components/sections/Stats/StatsSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pharma Logistic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="bg-gray-50 mx-auto">
        <RegularLayout>
          <HeroSection />
          <CategoriesSection />
          <StatsSection />
        </RegularLayout>
      </main>
    </>
  );
}
