import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import RegularLayout from "@/components/layout/regularLayout";
import CategoriesSection from "@/components/sections/Categories/CategoriesSection";
import HeroSection from "@/components/sections/Hero/HeroSection";
import StatsSection from "@/components/sections/Stats/StatsSection";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-50 mx-auto">
        <RegularLayout>
          <HeroSection />
          <CategoriesSection />
          <StatsSection />
        </RegularLayout>
      </main>
    </>
  );
}
