import RegularLayout from "@/layout/regularLayout";
import Head from "next/head";
import React from "react";

const Service = () => {
    return (
    <>
      <Head>
        <title>Pharma Logistic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="bg-gray-50 mx-auto">
        <RegularLayout>servicio</RegularLayout>
      </main>
    </>
  );
};

export default Service;
